spring.application.name=biometric-zone-gate-api

# Database configuration
# Connection URL to the database; change to the production URL as needed
spring.datasource.url = jdbc:mysql://192.168.0.204:3306/bzgdb

# Database credentials
#spring.datasource.username = icmdb
#spring.datasource.password = dakar*2024

# Hibernate: automatically updates the database schema on application startup
spring.jpa.hibernate.ddl-auto = update

# Server configuration
# Port running
server.port = 7070

# New Secret Key
jwt.secret.key = a1c9a1ebc37ca4585b61c98489fb0fd672cf81c924de784b636f59304017e64944fac9f4caeda08228899726a8c546f8

# JWT expiration time in milliseconds (1 day)
jwt.time.expiration = 1368000000

# Email configuration
email.sender = ing.cm.sac@gmail.com
email.password = vnkuttxyifnndztu

# MQTT server configuration
mqtt.serverUri = tcp://localhost:1883
mqtt.topic = bzgdb

#logging.level.org.springframework=DEBUG

# storage folder
file.image =  /var/www/bzgdb/files-storage
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 80MB
spring.servlet.multipart.max-request-size = 80MB